In [ ]:
import numpy as np


In [3]:
arr=np.array([5,10,15,20,25])

In [6]:
print(arr)
arr.dtype

[ 5 10 15 20 25]


dtype('int64')

In [10]:
print(arr*3)
print(arr+2)
print(arr/2)

[15 30 45 60 75]
[ 7 12 17 22 27]
[ 2.5  5.   7.5 10.  12.5]


In [16]:
brr=np.array([1,2,3,6,5,4])
crr=brr[::-1]
print(crr)

drr=np.flip(brr)
print(drr)

[4 5 6 3 2 1]
[4 5 6 3 2 1]


In [22]:
err=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(err[0,1])
print(err[2,0])

20
70


In [24]:
import numpy as np
sargun=np.linspace(10,100,25)
print(sargun)
print("dim:",sargun.ndim)
print("shape:",sargun.shape)
print("size:",sargun.size)
print("d_type :",sargun.dtype)
print("bytes:",sargun.nbytes)
transpose_arr=sargun.reshape(25,1)
print("transpose :",transpose_arr)

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
dim: 1
shape: (25,)
size: 25
d_type : float64
bytes: 200
transpose : [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]


In [25]:

import numpy as np
ucs420_sargun= np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 15, 20, 35]])
print( np.mean(ucs420_sargun))
print(np.median(ucs420_sargun))
print(np.max(ucs420_sargun))
print(np.min(ucs420_sargun))
print(np.unique(ucs420_sargun))
reshape_ucs420_sargun=ucs420_sargun.reshape(4,3)
print("reshape:",reshape_ucs420_sargun)
resize_ucs420_sargun=np.resize(ucs420_sargun,(2,6))
print("resize_array:",resize_ucs420_sargun)

43.333333333333336
37.5
90
10
[10 15 20 30 35 40 50 60 70 80 90]
reshape: [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
resize_array: [[10 20 30 40 50 60]
 [70 80 90 15 20 35]]
